name: Build iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3

      - name: Install Haxe Libraries
        run: |
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.6.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install hxCodec 3.0.2 || true
          haxelib git faxe https://github.com/as3boyan/faxe || true
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc || true

      - name: Compile iOS Xcode Project
        run: haxelib run lime build ios -release

      - name: Build IPA with Xcode
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir -p Payload
          cp -r *.app Payload/
          zip -r -9 output.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: export/release/ios/build/Release-iphoneos/output.ipa
