name: Build iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxe Libraries
        run: |
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install hxvlc --quiet
          haxelib git faxe https://github.com/as3boyan/faxe --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet

      - name: Compile iOS Xcode Project
        run: haxelib run lime build ios -release -nosign

      - name: Build IPA with Xcode
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir -p Payload
          cp -r *.app Payload/
          zip -r -9 output.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: export/release/ios/build/Release-iphoneos/*.ipa
